// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AlintaTestEvgeny.RESTful.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Movie
    {
        /// <summary>
        /// Initializes a new instance of the Movie class.
        /// </summary>
        public Movie() { }

        /// <summary>
        /// Initializes a new instance of the Movie class.
        /// </summary>
        public Movie(string name = default(string), IList<Role> roles = default(IList<Role>))
        {
            Name = name;
            Roles = roles;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roles")]
        public IList<Role> Roles { get; set; }

    }
}
